### ISSUE TITLE
검색창에서 아무것도 입력 안하고 엔터시 통신 오류

### ISSUE THREAD

**Issue by ilsubyeega** [Team-Mask-On/Mask_On#39]
## 어떤 bug 인가요? 
왼쪽 상단의 검색창에서 아무것도 입력하기 않고 엔터를 누를 경우 아래와 같은 문제가 발생합니다.
## 에러 메시지 또는 스크린샷
요청되는 주소: http://dapi.kakao.com/v2/local/search/keyword.json?query=&page=1&size=15
![image](https://user-images.githubusercontent.com/37479424/107177432-315d7d00-6a15-11eb-828b-542b1267bcba.png)

## bug 확인 방법
1. bug 위치 
![image](https://user-images.githubusercontent.com/37479424/107177446-36bac780-6a15-11eb-8e6a-76b34692081e.png)

## tried out solution
해결 방법을 직접 확인하지 않아서 모르겠지만, 아래의 코드 문제로 추측됩니다.
https://github.com/Team-Mask-On/Mask_On/blob/7b0c4bb9ba094b7918a32c85a8bde444921b4dd2/front/kakao/src/Components/SearchBar.js#L83
https://github.com/Team-Mask-On/Mask_On/blob/7b0c4bb9ba094b7918a32c85a8bde444921b4dd2/front/kakao/src/Components/KakaoMap.js#L71

추가로 만약에 가능하다면, 전체 센서의 목록을 가져오는 방법도 좋을것 같습니다.

감사합니다.

**Comment by Yabby1997** [comment]
안녕하세요, 이슈남겨주셔서 감사합니다. 

발생한 문제는 카카오지도 api에서 키워드 검색을 수행할 시에 필수로 입력되어야하는 파라미터인 키워드 문자열이
위에서 지적해주신대로 '아무것도 입력하지 않고 엔터를 누를 경우' 공백으로 전달되어 발생하는것으로 보입니다.
이와 관련하여 검색창에 아무것도 입력되지 않은 상황에 대한 예외처리를 하도록 하겠습니다.

해당 문제를 지적해주셔서 감사합니다😀

**Comment by ilsubyeega** [comment]
이미 패치된것으로 보아하니 이 이슈는 close 하겠습니다. 감사합니다.
